Name     : rubygem-vulcan
Version  : 0.8.2
Release  : 7
URL      : https://rubygems.org/downloads/vulcan-0.8.2.gem
Source0  : https://rubygems.org/downloads/vulcan-0.8.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: rubygem-vulcan-bin
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-hoe
BuildRequires : rubygem-multipart-post
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rest-client
BuildRequires : rubygem-rspec-core
Patch0: 0001-Remove-fake-dependency.patch 

%description


%package bin
Summary: bin components for the rubygem-vulcan package.
Group: Binaries

%description bin
bin components for the rubygem-vulcan package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n vulcan-0.8.2
%patch0 -p1
gem spec %{SOURCE0} -l --ruby > rubygem-vulcan.gemspec

%build
gem build rubygem-vulcan.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
vulcan-0.8.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/vulcan-0.8.2.gem
/usr/lib64/ruby/gems/2.2.0/doc/vulcan-0.8.2/ri/Vulcan/CLI/action-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/vulcan-0.8.2/ri/Vulcan/CLI/build-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/vulcan-0.8.2/ri/Vulcan/CLI/cdesc-CLI.ri
/usr/lib64/ruby/gems/2.2.0/doc/vulcan-0.8.2/ri/Vulcan/CLI/config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/vulcan-0.8.2/ri/Vulcan/CLI/config_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/vulcan-0.8.2/ri/Vulcan/CLI/create-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/vulcan-0.8.2/ri/Vulcan/CLI/error-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/vulcan-0.8.2/ri/Vulcan/CLI/heroku-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/vulcan-0.8.2/ri/Vulcan/CLI/heroku_git_domain-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/vulcan-0.8.2/ri/Vulcan/CLI/read_config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/vulcan-0.8.2/ri/Vulcan/CLI/server_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/vulcan-0.8.2/ri/Vulcan/CLI/update-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/vulcan-0.8.2/ri/Vulcan/CLI/write_config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/vulcan-0.8.2/ri/Vulcan/cdesc-Vulcan.ri
/usr/lib64/ruby/gems/2.2.0/doc/vulcan-0.8.2/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/README.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/bin/vulcan
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/lib/vulcan.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/lib/vulcan/cli.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/lib/vulcan/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/Procfile
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/bin/vulcan-make
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/bin/web
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/lib/cloudant.coffee
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/lib/logger.coffee
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/lib/on.coffee
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/lib/spawner.coffee
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/CNAME
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/README
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/bin/cake
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/bin/coffee
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/extras/jsl.conf
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/lib/coffee-script/browser.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/lib/coffee-script/cake.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/lib/coffee-script/coffee-script.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/lib/coffee-script/command.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/lib/coffee-script/grammar.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/lib/coffee-script/helpers.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/lib/coffee-script/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/lib/coffee-script/lexer.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/lib/coffee-script/nodes.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/lib/coffee-script/optparse.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/lib/coffee-script/parser.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/lib/coffee-script/repl.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/lib/coffee-script/rewriter.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/lib/coffee-script/scope.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/coffee-script/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/History.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/Makefile
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/Readme.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/index.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/lib/connect-form.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/Makefile
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/Readme.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/TODO
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/benchmark/bench-multipart-parser.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/example/post.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/example/upload.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/lib/file.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/lib/incoming_form.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/lib/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/lib/multipart_parser.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/lib/querystring_parser.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/lib/util.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/test/common.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/test/fixture/file/funkyfilename.txt
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/test/fixture/file/plain.txt
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/test/fixture/http/special-chars-in-filename/info.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/test/fixture/js/no-filename.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/test/fixture/js/special-chars-in-filename.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/test/fixture/multipart.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/test/integration/test-fixtures.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/test/legacy/common.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/test/legacy/integration/test-multipart-parser.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/test/legacy/simple/test-file.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/test/legacy/simple/test-incoming-form.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/test/legacy/simple/test-multipart-parser.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/test/legacy/simple/test-querystring-parser.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/test/legacy/system/test-multi-video-upload.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/test/run.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/test/unit/test-incoming-form.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/node_modules/formidable/tool/record.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/History.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/Makefile
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/README.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/benchmarks/graph
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/benchmarks/hello-world/connect.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/benchmarks/hello-world/node.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/benchmarks/hello-world/rack.thin.ru
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/benchmarks/hello-world/sinatra.thin.ru
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/benchmarks/public/jquery.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/benchmarks/run
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/benchmarks/static/connect.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/benchmarks/static/node.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/benchmarks/static/sinatra.thin.ru
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/api.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/bodyDecoder.1
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/bodyDecoder.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/bodyDecoder.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/compiler.1
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/compiler.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/compiler.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/conditionalGet.1
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/conditionalGet.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/conditionalGet.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/cookieDecoder.1
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/cookieDecoder.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/cookieDecoder.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/errorHandler.1
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/errorHandler.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/errorHandler.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/format.1
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/format.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/format.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/index.1
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/index.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/index.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/jsonrpc.1
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/jsonrpc.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/jsonrpc.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/layout/api.foot.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/layout/api.head.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/lint.1
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/lint.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/lint.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/logger.1
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/logger.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/logger.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/methodOverride.1
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/methodOverride.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/methodOverride.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/responseTime.1
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/responseTime.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/responseTime.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/router.1
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/router.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/router.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/session.1
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/session.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/session.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/staticProvider.1
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/staticProvider.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/docs/staticProvider.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/error/app.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/jsonrpc/app.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/less/app.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/less/public/index.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/less/public/style.less
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/lint/app.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/multitouch/app.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/multitouch/public/client.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/multitouch/public/favicon.ico
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/multitouch/public/index.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/multitouch/public/raphael.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/multitouch/public/style.css
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/router/app.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/sass/app.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/sass/public/index.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/sass/public/style.sass
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/session/app.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/stack-middleware/app.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/stack-middleware/hello.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/stack-middleware/world.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/static/app.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/static/public/style.css
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/url-rewrite/app.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/examples/vhost/app.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/install.sh
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/bodyDecoder.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/cache.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/cacheManifest.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/compiler.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/conditionalGet.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/cookieDecoder.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/errorHandler.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/format.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/gzip-compress.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/gzip-proc.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/gzip.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/jsonrpc.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/lint.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/logger.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/methodOverride.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/pubsub.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/repl.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/responseTime.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/router.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/session.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/session/memory.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/session/session.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/session/store.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/staticProvider.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/middleware/vhost.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/public/error.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/public/style.css
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/response.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/lib/connect/utils.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/support/highlight.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/bodyDecoder.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/compiler.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/connect.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/cookieDecoder.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/errorHandler.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/filters/uppercase.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/fixtures/foo.bar.baz.sass
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/fixtures/index.html
"/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/fixtures/some text.txt"
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/fixtures/style.less
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/fixtures/style.sass
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/fixtures/user.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/format.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/gzip.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/helpers/http.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/helpers/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/jsonrpc.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/logger.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/methodOverride.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/providers/echo.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/responseTime.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/router.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/session.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/static.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/utils.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/connect/test/vhost.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/expresso/History.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/expresso/Makefile
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/expresso/Readme.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/expresso/bin/expresso
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/expresso/lib/bar.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/expresso/lib/foo.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/expresso/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/expresso/seed.yml
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/expresso/test/assert.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/expresso/test/bar.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/expresso/test/foo.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/support/expresso/test/http.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/connect-form/test/form.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/README.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/lib/cradle.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/lib/cradle/cache.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/lib/cradle/database/attachments.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/lib/cradle/database/changes.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/lib/cradle/database/documents.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/lib/cradle/database/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/lib/cradle/database/views.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/lib/cradle/response.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/README.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/api.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/browser/eventemitter2.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/browser/export.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/browser/index.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/browser/jquery-1.6.1.min.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/browser/log4js.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/browser/main.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/browser/querystring.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/browser/request.jquery.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/browser/require.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/browser/util.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/cli.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/lib/feed.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/lib/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/lib/stream.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/node_modules/request/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/node_modules/request/README.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/node_modules/request/main.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/node_modules/request/mimetypes.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/node_modules/request/oauth.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/node_modules/request/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/node_modules/request/tests/googledoodle.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/node_modules/request/tests/run.sh
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/node_modules/request/tests/server.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/node_modules/request/tests/test-body.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/node_modules/request/tests/test-cookie.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/node_modules/request/tests/test-cookiejar.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/node_modules/request/tests/test-errors.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/node_modules/request/tests/test-oauth.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/node_modules/request/tests/test-pipes.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/node_modules/request/tests/test-proxy.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/node_modules/request/tests/test-timeout.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/node_modules/request/uuid.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/node_modules/request/vendor/cookie/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/node_modules/request/vendor/cookie/jar.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/test/couch.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/test/follow.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/test/issues.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/test/issues/10.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/follow/test/stream.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/README.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/forever.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/main.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/mimetypes.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/oauth.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/googledoodle.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/run.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/server.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/squid.conf
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/ssl/ca/ca.cnf
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/ssl/ca/ca.crl
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/ssl/ca/ca.crt
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/ssl/ca/ca.csr
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/ssl/ca/ca.key
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/ssl/ca/ca.srl
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/ssl/ca/server.cnf
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/ssl/ca/server.crt
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/ssl/ca/server.csr
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/ssl/ca/server.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/ssl/ca/server.key
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/ssl/npm-ca.crt
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/ssl/test.crt
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/ssl/test.key
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/test-body.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/test-cookie.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/test-cookiejar.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/test-defaults.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/test-errors.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/test-headers.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/test-httpModule.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/test-https-strict.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/test-https.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/test-oauth.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/test-params.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/test-pipes.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/test-proxy.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/test-qs.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/test-redirect.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/test-timeout.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/test-toJSON.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tests/test-tunnel.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/tunnel.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/uuid.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/vendor/cookie/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/request/vendor/cookie/jar.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/vargs/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/vargs/README.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/vargs/lib/vargs.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/node_modules/vargs/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/test/cache-test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/test/connection-test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/test/database-attachment-test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/test/database-cache-test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/test/database-test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/test/database-view-test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/test/fixtures/databases.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/test/helpers/seed.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/cradle/test/response-test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/History.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/Makefile
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/Readme.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/bin/express
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib-cov/application.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib-cov/express.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib-cov/middleware.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib-cov/request.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib-cov/response.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib-cov/router/collection.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib-cov/router/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib-cov/router/methods.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib-cov/router/route.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib-cov/utils.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib-cov/view.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib/express.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib/http.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib/https.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib/request.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib/response.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib/router/collection.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib/router/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib/router/methods.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib/router/route.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib/utils.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib/view.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib/view/partial.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/lib/view/view.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/cache.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/connect.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/http.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/https.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/basicAuth.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/compiler.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/csrf.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/directory.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/errorHandler.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/favicon.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/limit.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/logger.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/methodOverride.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/profiler.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/query.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/responseTime.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/router.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/session.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/session/cookie.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/session/memory.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/session/session.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/session/store.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/static.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/staticCache.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/middleware/vhost.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/patch.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/directory.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/error.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/favicon.ico
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_add.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_attach.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_code.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_copy.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_delete.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_edit.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_error.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_excel.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_find.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_gear.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_go.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_green.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_key.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_lightning.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_link.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_paintbrush.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_paste.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_red.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_refresh.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_save.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_acrobat.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_actionscript.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_add.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_c.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_camera.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_cd.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_code.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_code_red.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_coldfusion.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_compressed.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_copy.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_cplusplus.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_csharp.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_cup.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_database.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_delete.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_dvd.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_edit.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_error.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_excel.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_find.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_flash.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_freehand.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_gear.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_get.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_go.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_h.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_horizontal.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_key.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_lightning.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_link.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_magnify.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_medal.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_office.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_paint.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_paintbrush.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_paste.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_php.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_picture.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_powerpoint.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_put.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_ruby.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_stack.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_star.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_swoosh.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_text.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_text_width.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_tux.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_vector.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_visualstudio.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_width.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_word.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_world.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_wrench.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_white_zip.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_word.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/icons/page_world.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/public/style.css
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/lib/utils.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/Makefile
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/Readme.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/TODO
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/benchmark/bench-multipart-parser.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/example/post.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/example/upload.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/lib/file.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/lib/incoming_form.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/lib/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/lib/multipart_parser.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/lib/querystring_parser.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/lib/util.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/test/common.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/test/fixture/file/funkyfilename.txt
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/test/fixture/file/plain.txt
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/test/fixture/http/special-chars-in-filename/info.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/test/fixture/js/no-filename.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/test/fixture/js/special-chars-in-filename.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/test/fixture/multipart.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/test/integration/test-fixtures.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/test/legacy/common.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/test/legacy/integration/test-multipart-parser.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/test/legacy/simple/test-file.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/test/legacy/simple/test-incoming-form.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/test/legacy/simple/test-multipart-parser.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/test/legacy/simple/test-querystring-parser.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/test/legacy/system/test-multi-video-upload.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/test/run.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/test/unit/test-incoming-form.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/node_modules/formidable/tool/record.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/connect/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mime/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mime/README.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mime/mime.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mime/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mime/test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mime/types/mime.types
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mime/types/node.types
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mkdirp/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mkdirp/README.markdown
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mkdirp/examples/pow.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mkdirp/examples/pow.js.orig
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mkdirp/examples/pow.js.rej
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mkdirp/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mkdirp/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mkdirp/test/chmod.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mkdirp/test/clobber.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mkdirp/test/mkdirp.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mkdirp/test/perm.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mkdirp/test/perm_sync.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mkdirp/test/race.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mkdirp/test/rel.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mkdirp/test/sync.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mkdirp/test/umask.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/mkdirp/test/umask_sync.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/qs/History.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/qs/Makefile
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/qs/Readme.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/qs/benchmark.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/qs/examples.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/qs/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/qs/lib/querystring.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/qs/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/qs/test/mocha.opts
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/qs/test/parse.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/node_modules/qs/test/stringify.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/express/test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/History.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/Makefile
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/Readme.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/index.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/lib/knox/auth.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/lib/knox/client.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/lib/knox/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/lib/knox/mime/README.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/lib/knox/mime/mime.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/lib/knox/mime/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/lib/knox/mime/test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/lib/knox/utils.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/support/expresso/History.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/support/expresso/Makefile
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/support/expresso/Readme.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/support/expresso/bin/expresso
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/support/expresso/docs/api.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/support/expresso/docs/index.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/support/expresso/docs/index.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/support/expresso/docs/layout/foot.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/support/expresso/docs/layout/head.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/support/expresso/lib/bar.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/support/expresso/lib/foo.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/support/expresso/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/support/expresso/test/assert.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/support/expresso/test/async.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/support/expresso/test/bar.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/support/expresso/test/foo.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/support/expresso/test/http.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/support/expresso/test/serial/async.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/support/expresso/test/serial/http.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/test/auth.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/test/fixtures/user.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/test/knox.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/knox/test/utils.test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/node-uuid/LICENSE.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/node-uuid/README.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/node-uuid/benchmark/README.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/node-uuid/benchmark/bench.gnu
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/node-uuid/benchmark/bench.sh
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/node-uuid/benchmark/benchmark-native.c
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/node-uuid/benchmark/benchmark.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/node-uuid/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/node-uuid/test/compare_v1.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/node-uuid/test/test.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/node-uuid/test/test.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/node-uuid/uuid.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/nodemon/README.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/nodemon/nodemon.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/nodemon/nodemonignore.example
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/nodemon/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/restler/MIT-LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/restler/README.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/restler/bin/restler
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/restler/index.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/restler/lib/multipartform.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/restler/lib/restler.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/restler/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/restler/test/all.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/node_modules/restler/test/restler.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/package.json
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/bin/restclient
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/cache/couchrest-1.1.2.gem
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/cache/mime-types-1.16.gem
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/cache/multi_json-1.0.3.gem
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/cache/rest-client-1.6.7.gem
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/README.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/THANKS.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/VERSION
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/couchrest.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/examples/word_count/markov
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/examples/word_count/views/books/chunked-map.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/examples/word_count/views/books/united-map.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/examples/word_count/views/markov/chain-map.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/examples/word_count/views/markov/chain-reduce.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/examples/word_count/views/word_count/count-map.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/examples/word_count/views/word_count/count-reduce.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/examples/word_count/word_count.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/examples/word_count/word_count_query.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/examples/word_count/word_count_views.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/history.txt
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/init.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/lib/couchrest.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/lib/couchrest/attributes.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/lib/couchrest/commands/generate.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/lib/couchrest/commands/push.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/lib/couchrest/database.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/lib/couchrest/design.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/lib/couchrest/document.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/lib/couchrest/helper/attachments.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/lib/couchrest/helper/pager.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/lib/couchrest/helper/streamer.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/lib/couchrest/helper/upgrade.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/lib/couchrest/middlewares/logger.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/lib/couchrest/monkeypatches.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/lib/couchrest/rest_api.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/lib/couchrest/server.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/lib/couchrest/support/inheritable_attributes.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/spec/couchrest/couchrest_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/spec/couchrest/database_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/spec/couchrest/design_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/spec/couchrest/document_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/spec/couchrest/helpers/pager_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/spec/couchrest/helpers/streamer_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/spec/couchrest/rest_api_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/spec/couchrest/server_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/spec/fixtures/attachments/README
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/spec/fixtures/attachments/couchdb.png
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/spec/fixtures/attachments/test.html
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/spec/fixtures/views/lib.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/spec/fixtures/views/test_view/lib.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/spec/fixtures/views/test_view/only-map.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/spec/fixtures/views/test_view/test-map.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/spec/fixtures/views/test_view/test-reduce.js
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/spec/spec.opts
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/utils/remap.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/couchrest-1.1.2/utils/subset.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/mime-types-1.16/History.txt
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/mime-types-1.16/Install.txt
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/mime-types-1.16/Licence.txt
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/mime-types-1.16/Manifest.txt
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/mime-types-1.16/README.txt
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/mime-types-1.16/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/mime-types-1.16/lib/mime/types.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/mime-types-1.16/lib/mime/types.rb.data
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/mime-types-1.16/mime-types.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/mime-types-1.16/setup.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/mime-types-1.16/test/test_mime_type.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/mime-types-1.16/test/test_mime_types.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/multi_json-1.0.3/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/multi_json-1.0.3/LICENSE.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/multi_json-1.0.3/README.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/multi_json-1.0.3/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/multi_json-1.0.3/lib/multi_json.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/multi_json-1.0.3/lib/multi_json/engines/json_gem.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/multi_json-1.0.3/lib/multi_json/engines/json_pure.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/multi_json-1.0.3/lib/multi_json/engines/ok_json.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/multi_json-1.0.3/lib/multi_json/engines/yajl.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/multi_json-1.0.3/lib/multi_json/vendor/ok_json.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/multi_json-1.0.3/lib/multi_json/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/multi_json-1.0.3/multi_json.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/multi_json-1.0.3/spec/helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/multi_json-1.0.3/spec/multi_json_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/VERSION
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/bin/restclient
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/history.md
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/lib/rest-client.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/lib/rest_client.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/lib/restclient.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/lib/restclient/exceptions.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/lib/restclient/payload.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/lib/restclient/raw_response.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/lib/restclient/request.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/lib/restclient/resource.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/lib/restclient/response.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/spec/abstract_response_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/spec/base.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/spec/exceptions_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/spec/integration/certs/equifax.crt
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/spec/integration/certs/verisign.crt
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/spec/integration/request_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/spec/integration_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/spec/master_shake.jpg
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/spec/payload_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/spec/raw_response_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/spec/request2_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/spec/request_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/spec/resource_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/spec/response_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/gems/rest-client-1.6.7/spec/restclient_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/specifications/couchrest-1.1.2.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/specifications/mime-types-1.16.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/specifications/multi_json-1.0.3.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/vendor/gems/specifications/rest-client-1.6.7.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/vulcan-0.8.2/server/web.coffee
/usr/lib64/ruby/gems/2.2.0/specifications/vulcan-0.8.2.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/vulcan
